---
- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Install System Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items:
    - curl
    - wget
    - python-software-properties

- name: Install Extra Packages
  sudo: yes
  apt: pkg={{ item }} state=latest
  with_items: server.packages
  when: server.packages is defined

- name: Configure the timezone
  sudo: yes
  template: src=timezone.tpl dest=/etc/timezone

- name: More Configure the timezone
  sudo: yes
  file: src=/usr/share/zoneinfo/{{server.timezone}} dest=/etc/localtime state=link force=yes backup=yes

- name: Set default system language pack
  shell: locale-gen {{server.locale}}
  sudo: yes

- name: Remount with acl
  sudo: yes
  shell: mount -o remount,acl /

- name: Create /var/www/html dir
  file: path=/var/www/html state=directory recurse=yes owner=www-data group=www-data

- name: Create projects dir
  file: path=/home/vagrant/projects state=directory recurse=yes owner=vagrant group=vagrant

- name: Check if swap exists
  stat: path=/var/swap.1
  register: swap_dir

- name: Add swap for composer
  sudo: yes
  shell: "{{ item }}"
  with_items:
    - df -h
    - dd if=/dev/zero of=/swapfile bs=1M count=1024
    - dd if=/dev/zero of=/swapfile bs=1M count=1024
    - mkswap /swapfile
    - chmod 600 /swapfile
    - mkswap /swapfile
    - swapon /swapfile
    - echo 'echo "/swapfile  none  swap  defaults  0  0" >> /etc/fstab' | sudo sh
    - free -m
  when: swap_dir.stat.exists == false

