---
server:
    install: '1'
    packages: [imagemagick, nodejs, npm, git]
    timezone: Europe/Berlin
    locale: de_DE.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: vagrant-lamp, ip: 192.168.33.12, memory: '1024', sharedfolder: ./src, useVagrantCloud: '1', syncType: '0' }
nginx:
    install: '1'
    docroot: /vagrant
    servername: myApp.vb
mysql:
    install: '1'
    root_password: '123'
    database: symfony
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-imagick, php-pear, php5-mysql, php5-common, php5-gd, php5-xmlrpc, php5-xsl, php5-xdebug]
xdebug:
    install: '1'
composer:
    install: '1'

