---
server:
    install: '1'
    packages: [git, imagemagick, nodejs, npm, acl]
    timezone: Europe/Berlin
    locale: de_DE.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: vagrant-lamp, ip: 192.168.33.12, memory: '1024', sharedfolder: ./src, useVagrantCloud: '1', syncType: '0' }
apache:
    install: '1'
    docroot: /var/www/html
    servername: vagrant-lamp
mysql:
    install: '1'
    root_password: '123'
    database: symfony
    user: user
    password: password
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php-pear, php5-curl, php5-imagick, php5-common, php5-mysql, php5-xdebug, php5-xmlrpc, php5-xsl, php5-mbstring]
    peclpackages: [APC, mysql, PDO, PDO_MYSQL]
xdebug:
    install: '1'
composer:
    install: '1'
symfony:
    install: '1'
    version: '2.7'
    project_name: 'example'
    project_home: '/home/vagrant/projects'





