---
- name: Check if project example exists
  stat: path={{symfony.project_home}}/{{symfony.project_name}}/web
  register: example_dir

- name: Create new example project
  sudo: no
  shell: composer --no-interaction --prefer-dist create-project symfony/framework-standard-edition {{symfony.project_home}}/{{symfony.project_name}} "{{symfony.version}}.*"
  when: example_dir.stat.exists == false

- name: Check if project config dir
  stat: path={{symfony.project_home}}/{{symfony.project_name}}/app/config
  register: config_dir

- name: Update parameters config
  sudo: no
  template: src=parameters.yml.tpl dest={{symfony.project_home}}/{{symfony.project_name}}/app/config/parameters.yml
  when: config_dir.stat.exists == true


