---
- name: Check if project example exists
  stat: path={{symfony.project_home}}/{{symfony.project_name}}
  register: example_dir

- name: Create new example project
  shell: "{{ item }}"
  with_items:
  - cd {{symfony.project_home}}
  - composer --no-dev --optimize-autoloader --no-interaction create-project symfony/framework-standard-edition {{symfony.project_name}} "{{symfony.version}}.*"
  when: example_dir.stat.exists == false

- name: Check if project config dir
  stat: path={{symfony.project_home}}/{{symfony.project_name}}/app/config
  register: config_dir

- name: Update parameters config
  template: src=parameters.yml.tpl dest={{app.contao.home}}/app/config/parameters.yml
  when: config_dir.stat.exists == true


